# Generated by Django 4.1 on 2023-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MediaRating',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MediaViews',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
