# Generated by Django 4.1 on 2023-05-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_media_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaRating',
        ),
        migrations.DeleteModel(
            name='MediaViews',
        ),
    ]
