# Generated by Django 4.1 on 2023-05-06 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0003_delete_mediarating_delete_mediaviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaViews',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mediaId', models.BigIntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
