# Generated by Django 4.1 on 2023-05-07 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_mediarating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarating',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
