# Generated by Django 4.1 on 2023-05-07 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_mediarating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarating',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
