# Generated by Django 4.1 on 2023-05-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_mediaviews_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaviews',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
