# Generated by Django 4.1 on 2023-05-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_mediaviews_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
